app = "new-api-andy"
primary_region = "nrt"

[build]
  dockerfile = "Dockerfile"

[env]
  TZ = "Asia/Shanghai"
  PORT = "3000"
  SQL_DSN = "/data/new-api.db"
  REDIS_CONN_STRING = ""
  ERROR_LOG_ENABLED = "true"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[mounts]]
  source = "new_api_data"
  destination = "/data"

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  path = "/api/status"
  timeout = "5s"